DROP DATABASE IF EXISTS db_empManager;
CREATE DATABASE db_empManager;

USE db_empManager;

CREATE TABLE Department (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE Roles (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(30) NOT NULL,
    SALARY DECIMAL(10,2),
    DEPARTMENT_ID INTEGER,
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES Department(ID)
    ON DELETE SET NULL
);

CREATE TABLE Employee (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    ROLE_ID INTEGER,
    FOREIGN KEY (ROLE_ID)
    REFERENCES Roles(ID)
    ON DELETE SET NULL
);